### ISSUE TITLE
Theme blade

### ISSUE THREAD

**Issue by ghermans** [idevelopment/voicetank#62]
For the current moment we have multiple blades in the layouts folder.
These files need to be merges into one blade.

**Menu links for guests**
- Home
- FAQ
- Contact

**Menu links for users**
- Home
- FAQ
- Contact

**Menu links for admins**
- Home
- Categories
- Labels
- Feedback
- FAQ
- Reports
- [ ] Users (dropdown)
- Roles

**Comment by Tjoosten** [comment]
@ghermans pr needs review. It pr is ok you can close this one.

**Comment by Tjoosten** [comment]
@ghermans pr needs review. It pr is ok you can close this one.

**Comment by Tjoosten** [comment]
@ghermans can you update the users dropdown in the description; So i know what needs to be stand in the dropdown.
